services:
  db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_batik_pso
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
